### ISSUE TITLE
Error in Chapter 11, language_survey.py and survey.py

### ISSUE THREAD

**Issue by savorocks** [ehmatthes/pcc#55]
Hi,

I get the following error when i try to run language_survey.py:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/savo/python/pythoncrash/book/chapter_11/language_survey.py", line 8, in <module>
    my_survey.show_question()
  File "/home/savo/python/pythoncrash/survey.py", line 11, in show_question
    
NameError: name 'question' is not defined

I checked multiple times for typos, then downloaded the code from github and tried to run it - got the same error. I can't figure out what it is. 

P.S. i changed the working directory accordingly with os.chdir(), so it's not that

**Comment by savorocks** [comment]
Apparently the problem was with my python interpreter running in emacs. Restarted it, and everything works fine. Sorry for disturbance.
